// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/poa/poa.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AddValidatorProposal is a gov Content type for adding a validator
type AddValidatorProposal struct {
	// title of the proposal
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// description of the proposal
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// validator address to add
	// string validator_address = 3 [(cosmos_proto.scalar) = "cosmos.AddressString"];
	ValidatorAddress string `protobuf:"bytes,3,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *AddValidatorProposal) Reset()         { *m = AddValidatorProposal{} }
func (m *AddValidatorProposal) String() string { return proto.CompactTextString(m) }
func (*AddValidatorProposal) ProtoMessage()    {}
func (*AddValidatorProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_636a5c9e8ceed69c, []int{0}
}
func (m *AddValidatorProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddValidatorProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddValidatorProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddValidatorProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddValidatorProposal.Merge(m, src)
}
func (m *AddValidatorProposal) XXX_Size() int {
	return m.Size()
}
func (m *AddValidatorProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_AddValidatorProposal.DiscardUnknown(m)
}

var xxx_messageInfo_AddValidatorProposal proto.InternalMessageInfo

func (m *AddValidatorProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddValidatorProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AddValidatorProposal) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

// RemoveValidatorProposal is a gov Content type for removing a validator
type RemoveValidatorProposal struct {
	// title of the proposal
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// description of the proposal
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// validator address to remove
	ValidatorAddress string `protobuf:"bytes,3,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
}

func (m *RemoveValidatorProposal) Reset()         { *m = RemoveValidatorProposal{} }
func (m *RemoveValidatorProposal) String() string { return proto.CompactTextString(m) }
func (*RemoveValidatorProposal) ProtoMessage()    {}
func (*RemoveValidatorProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_636a5c9e8ceed69c, []int{1}
}
func (m *RemoveValidatorProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveValidatorProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoveValidatorProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoveValidatorProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveValidatorProposal.Merge(m, src)
}
func (m *RemoveValidatorProposal) XXX_Size() int {
	return m.Size()
}
func (m *RemoveValidatorProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveValidatorProposal.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveValidatorProposal proto.InternalMessageInfo

func (m *RemoveValidatorProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RemoveValidatorProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RemoveValidatorProposal) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*AddValidatorProposal)(nil), "packages.blockchain.poa.AddValidatorProposal")
	proto.RegisterType((*RemoveValidatorProposal)(nil), "packages.blockchain.poa.RemoveValidatorProposal")
}

func init() { proto.RegisterFile("blockchain/poa/poa.proto", fileDescriptor_636a5c9e8ceed69c) }

var fileDescriptor_636a5c9e8ceed69c = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0x41, 0x4a, 0x3b, 0x31,
	0x14, 0xc6, 0x9b, 0xff, 0x1f, 0x05, 0xe3, 0x46, 0x87, 0x81, 0x4e, 0xbb, 0x88, 0xa5, 0x2b, 0x37,
	0x4e, 0x16, 0x3d, 0x41, 0x0b, 0x2e, 0x85, 0x52, 0xc1, 0x85, 0x9b, 0x92, 0x49, 0x62, 0x1a, 0x3a,
	0x33, 0x2f, 0x24, 0x69, 0xb1, 0xb7, 0x70, 0x23, 0x78, 0x10, 0x0f, 0xe1, 0xb2, 0xb8, 0x72, 0x29,
	0x9d, 0x8b, 0xc8, 0x4c, 0xa6, 0x5a, 0x3c, 0x81, 0x8b, 0xc0, 0x7b, 0xdf, 0xf7, 0xfd, 0x92, 0xc0,
	0x7b, 0x38, 0xc9, 0x72, 0xe0, 0x4b, 0xbe, 0x60, 0xba, 0xa4, 0x06, 0x58, 0x7d, 0x52, 0x63, 0xc1,
	0x43, 0xd4, 0x35, 0x8c, 0x2f, 0x99, 0x92, 0x2e, 0xfd, 0x89, 0xa4, 0x06, 0x58, 0xbf, 0xa7, 0x00,
	0x54, 0x2e, 0x69, 0x13, 0xcb, 0x56, 0x0f, 0x94, 0x95, 0x9b, 0xc0, 0xf4, 0x63, 0x05, 0x0a, 0x9a,
	0x92, 0xd6, 0x55, 0xab, 0x5e, 0xfc, 0x06, 0xbc, 0x2e, 0xa4, 0xf3, 0xac, 0x30, 0x6d, 0xa0, 0xc7,
	0xc1, 0x15, 0xe0, 0xe6, 0x81, 0x0c, 0x4d, 0xb0, 0x86, 0xcf, 0x08, 0xc7, 0x63, 0x21, 0xee, 0x58,
	0xae, 0x05, 0xf3, 0x60, 0xa7, 0x16, 0x0c, 0x38, 0x96, 0x47, 0x31, 0x3e, 0xf2, 0xda, 0xe7, 0x32,
	0x41, 0x03, 0x74, 0x79, 0x32, 0x0b, 0x4d, 0x34, 0xc0, 0xa7, 0x42, 0x3a, 0x6e, 0xb5, 0xf1, 0x1a,
	0xca, 0xe4, 0x5f, 0xe3, 0x1d, 0x4a, 0xd1, 0x35, 0x3e, 0x5f, 0xef, 0x2f, 0x9b, 0x33, 0x21, 0xac,
	0x74, 0x2e, 0xf9, 0x5f, 0xe7, 0x26, 0xc9, 0xfb, 0xeb, 0x55, 0xdc, 0xbe, 0x3e, 0x0e, 0xce, 0xad,
	0xb7, 0xba, 0x54, 0xb3, 0xb3, 0x6f, 0xa4, 0xd5, 0x87, 0x2f, 0x08, 0x77, 0x67, 0xb2, 0x80, 0xb5,
	0xfc, 0x6b, 0x5f, 0x9b, 0xdc, 0xbc, 0xed, 0x08, 0xda, 0xee, 0x08, 0xfa, 0xdc, 0x11, 0xf4, 0x54,
	0x91, 0xce, 0xb6, 0x22, 0x9d, 0x8f, 0x8a, 0x74, 0xee, 0x47, 0x4a, 0xfb, 0xc5, 0x2a, 0x4b, 0x39,
	0x14, 0x74, 0x2a, 0xa5, 0x75, 0x1b, 0xe7, 0xe9, 0x7e, 0xcc, 0xf4, 0x60, 0x13, 0x1e, 0x9b, 0x5d,
	0xf0, 0x1b, 0x23, 0x5d, 0x76, 0xdc, 0x0c, 0x62, 0xf4, 0x15, 0x00, 0x00, 0xff, 0xff, 0x39, 0x3a,
	0xb5, 0xaf, 0x2a, 0x02, 0x00, 0x00,
}

func (m *AddValidatorProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddValidatorProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddValidatorProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintPoa(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintPoa(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintPoa(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RemoveValidatorProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveValidatorProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemoveValidatorProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintPoa(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintPoa(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintPoa(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPoa(dAtA []byte, offset int, v uint64) int {
	offset -= sovPoa(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AddValidatorProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovPoa(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovPoa(uint64(l))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovPoa(uint64(l))
	}
	return n
}

func (m *RemoveValidatorProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovPoa(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovPoa(uint64(l))
	}
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovPoa(uint64(l))
	}
	return n
}

func sovPoa(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPoa(x uint64) (n int) {
	return sovPoa(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AddValidatorProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoa
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddValidatorProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddValidatorProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoa
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoa
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoa
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoa(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoa
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveValidatorProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoa
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveValidatorProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveValidatorProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoa
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoa
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoa
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoa
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoa(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoa
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPoa(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPoa
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoa
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPoa
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPoa
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPoa
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPoa        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPoa          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPoa = fmt.Errorf("proto: unexpected end of group")
)
