name: GoReleaser
on:
  workflow_dispatch:
    inputs:
      commit_branch:
        description: The branch or the commit sha to push tag to
        required: true
  workflow_call:
    inputs:
      commit_branch:
        type: string
        description: The branch or the commit sha to push tag to
        required: true

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Free disk space
        run: rm -rf /opt/hostedtoolcache
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ inputs.commit_branch }}
          fetch-depth: 0
          fetch-tags: true
      - uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
      - uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      # Build and push docker image
      - name: Run go releaser
        run: |
          docker run --rm -e CGO_ENABLED -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
             -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/go/src/exrp -w /go/src/exrp \
             --entrypoint /bin/sh \
             goreleaser/goreleaser-cross:v1.22 -c \
             'git config --global --add safe.directory /go/src/exrp && goreleaser release --clean --skip validate'
