// Code generated by MockGen. DO NOT EDIT.
// Source: x/poa/testutil/tx.go

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"

	types "github.com/cosmos/cosmos-sdk/types"
	gomock "github.com/golang/mock/gomock"
	proto "google.golang.org/protobuf/proto"
)

// MockTx is a mock of Tx interface.
type MockTx struct {
	ctrl     *gomock.Controller
	recorder *MockTxMockRecorder
}

// MockTxMockRecorder is the mock recorder for MockTx.
type MockTxMockRecorder struct {
	mock *MockTx
}

// NewMockTx creates a new mock instance.
func NewMockTx(ctrl *gomock.Controller) *MockTx {
	mock := &MockTx{ctrl: ctrl}
	mock.recorder = &MockTxMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTx) EXPECT() *MockTxMockRecorder {
	return m.recorder
}

// GetMsgs mocks base method.
func (m *MockTx) GetMsgs() []types.Msg {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMsgs")
	ret0, _ := ret[0].([]types.Msg)
	return ret0
}

// GetMsgs indicates an expected call of GetMsgs.
func (mr *MockTxMockRecorder) GetMsgs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMsgs", reflect.TypeOf((*MockTx)(nil).GetMsgs))
}

// GetMsgsV2 mocks base method.
func (m *MockTx) GetMsgsV2() ([]proto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMsgsV2")
	ret0, _ := ret[0].([]proto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMsgsV2 indicates an expected call of GetMsgsV2.
func (mr *MockTxMockRecorder) GetMsgsV2() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMsgsV2", reflect.TypeOf((*MockTx)(nil).GetMsgsV2))
}
